[improve] Exclude log4j12 dependency conflicts，Fix the error [Detecte…
apache/streampark pull request #1637
Opened 2022-09-18 15:47 UTC by GuoNingNing

…d both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError]

Problem Summary:

### What is changed and how it works?

Proposal: [xxx](url) 

Feel free to ping committers for the review!

## Contribution Checklist

  - Make sure that the pull request corresponds to a [GITHUB issue](https://github.com/apache/streampark/issues).

  - Name the pull request in the form "[Feature] [component] Title of the pull request", where *Feature* can be replaced by `Hotfix`, `Bug`, etc.

  - Minor fixes should be named following this pattern: `[hotfix] [docs] Fix typo in README.md doc`.

## Purpose of this pull request

2022-09-18 15:55 UTC, lvshaokang requested changes

2022-09-18 15:55 UTC, lvshaokang commented on streampark-spark/pom.xml
>          <!--Spark Streaming 核心jar-->
Could you remove these non-ascaii characters?

2022-09-19 05:00 UTC, wolfboys approved these changes
LGTM

2022-09-19 05:26 UTC, lvshaokang approved these changes
LGTM. Thanks!

2022-09-19 05:28 UTC, merged