[Feature][Flink-K8s-V2] Add KubernetesApplicationClient.shutdown on Flink-Kubernetes-V2
apache/streampark pull request #3186
Opened 2023-09-25 09:17 UTC by caicancai

Add KubernetesApplicationClient.shutdown on Flink-Kubernetes-V2

## What changes were proposed in this pull request

Add KubernetesApplicationClient.shutdown on Flink-Kubernetes-V2

## Brief change log

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

KubernetesNativeApplicationClient.shutdown 适配到 [FlinkK8sOperator.delete](https://github.com/Al-assad/streampark-flink-kubernetes-v2/blob/master/src/main/scala/org/apache/streampark/flink/kubernetes/operator/FlinkK8sOperator.scala#L41);

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

2023-09-25 09:18 UTC, caicancai commented
cc @Al-assad @wolfboys

2023-09-25 09:29 UTC, caicancai commented
This function takes into account whether the user's intention to delete Application in SP is to delete deploy at the same time. The specific method must refer to other projects, so it is currently implemented separately in the v2 module.

2023-09-25 09:35 UTC, Al-assad requested changes

2023-09-25 09:35 UTC, Al-assad commented on streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/FlinkClientEndpoint.scala
> +        else _
The "else _" here will return a runtime error, Modify in pattern matching to `case KUBERNETES_NATIVE_APPLICATION if K8sFlinkConfig.isV2Enabled`

2023-09-25 09:35 UTC, Al-assad commented on streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesApplicationClientV2.scala
> +    FlinkK8sOperator.k8sCrOpr.deleteSessionJob(namespace, name).runIOAsTry match {
It should be implemented that in KubernetesApplicationClientV2, the task of removing the Application mode is actually removing the FlinkDeployment CR, not the SessionJob CR

2023-09-25 10:03 UTC, Al-assad commented
@caicancai  It seems that some errors occurred in the compilation

2023-09-25 12:08 UTC, caicancai commented
@Al-assad  tested

2023-09-25 13:07 UTC, Al-assad requested changes

2023-09-25 13:07 UTC, Al-assad commented on streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/FlinkClientEndpoint.scala
> +        K8sFlinkConfig.isV2Enabled match {
This is still an incorrect pattern matching branch line.
When KUBERNETES_NATIVE_APPLICATION = true and K8sFlinkConfig.isV2Enables = false, a match missing error will be thrown here.

2023-09-25 13:07 UTC, Al-assad commented on streampark-flink/streampark-flink-client/streampark-flink-client-core/src/main/scala/org/apache/streampark/flink/client/impl/KubernetesApplicationClientV2.scala
> +    FlinkK8sOperator.k8sCrOpr.deleteDeployment(namespace, name).runIOAsTry match {
If you directly use the `CROperator` internal API, you need to manually untrack the corresponding resources with `FlinkK8sObserver.untrack`.

2023-09-27 01:42 UTC, caicancai commented
cc @Al-assad

2023-10-08 10:24 UTC, Al-assad commented
@caicancai  This PR and PR#3216 have the same logical issue. I have fixed it in commit a993111.

2023-10-08 10:28 UTC, caicancai commented
> @caicancai This PR and PR#3216 have the same logical issue. I have fixed it in commit [a993111](https://github.com/apache/incubator-streampark/commit/a99311195cb1d85c5575368448e964aa6f1ff117).

thank you

2023-10-08 10:44 UTC, Al-assad approved these changes

2023-10-08 10:45 UTC, merged