[Improve] Optimize equals method conflicts
apache/streampark pull request #3528
Opened 2024-02-01 09:35 UTC by linweijiang

## What changes were proposed in this pull request

Issue Number: close #xxx 

## Brief change log

## Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

## Does this pull request potentially affect one of the following parts
 - Dependencies (does it add or upgrade a dependency): (yes / no)

2024-02-02 05:39 UTC, caicancai commented
Can you tell me why you changed it like this?

2024-02-02 08:34 UTC, linweijiang commented
> Can you tell me why you changed it like this?

When I execute the 'mvn install' command in a Windows environment, conflicts arise due to the lombok's @Data annotation, which by default implements an equals method that collides with the manually written equals method in the current class, resulting in the following exception: 
`Not generating hashCode: One of equals or hashCode exists. You should either write both of these or none of these (in the latter case, lombok generates them).`

2024-02-02 09:45 UTC, caicancai commented
> > Can you tell me why you changed it like this?
> 
> When I execute the 'mvn install' command in a Windows environment, conflicts arise due to the lombok's `@Data` annotation, which by default implements an equals method that collides with the manually written equals method in the current class, resulting in the following exception: `Not generating hashCode: One of equals or hashCode exists. You should either write both of these or none of these (in the latter case, lombok generates them).`

OK, thank you for your explanation and contribution. I will verify it and if there is no problem I will merge it. Can you please add the reason to the PR description?

2024-02-02 10:00 UTC, linweijiang commented
> > > Can you tell me why you changed it like this?
> > 
> > 
> > When I execute the 'mvn install' command in a Windows environment, conflicts arise due to the lombok's `@Data` annotation, which by default implements an equals method that collides with the manually written equals method in the current class, resulting in the following exception: `Not generating hashCode: One of equals or hashCode exists. You should either write both of these or none of these (in the latter case, lombok generates them).`
> 
> OK, thank you for your explanation and contribution. I will verify it and if there is no problem I will merge it. Can you please add the reason to the PR description?

I have added the description information. Can you help me to check it? This is my first time submitting a PR to our project, thank you.

2024-02-02 14:04 UTC, VampireAchao requested changes
Thank you for your submission. I've reviewed the changes and I'd like to suggest an alternative approach that might align better with our goals of minimizing code intrusion while retaining the flexibility of our model's accessors. Instead of changing @Data to @Getter, consider applying the lombok.experimental.Tolerate annotation on the equals method. This approach is less invasive as it preserves the setters, which might be beneficial for our use cases where setter methods are needed. Moreover, the Tolerate annotation is specifically designed for scenarios like this, allowing us to override method signatures without losing the benefits of Lombok's automatic generation features. I believe this will keep our code both clean and functional. Let me know if you have any questions or need further clarification on implementing this. Thanks!

2024-02-03 01:34 UTC, linweijiang commented
> Thank you for your submission. I've reviewed the changes and I'd like to suggest an alternative approach that might align better with our goals of minimizing code intrusion while retaining the flexibility of our model's accessors. Instead of changing @DaTa to @getter, consider applying the lombok.experimental.Tolerate annotation on the equals method. This approach is less invasive as it preserves the setters, which might be beneficial for our use cases where setter methods are needed. Moreover, the Tolerate annotation is specifically designed for scenarios like this, allowing us to override method signatures without losing the benefits of Lombok's automatic generation features. I believe this will keep our code both clean and functional. Let me know if you have any questions or need further clarification on implementing this. Thanks!

Thank you for your advice. After examining the usage of the class, I've noticed that there are no calls to functionalities provided by the `@Data` annotation other than the `@Getter`. Hence, it seems that only incorporating the `@Getter` annotation might be a better choice.

2024-02-03 02:47 UTC, wolfboys approved these changes
LGTM

2024-02-03 02:49 UTC, wolfboys commented
good job, Thanks for your contribution, Looking forward to your next contribution! 🙌

2024-02-03 02:50 UTC, VampireAchao commented
Thank you for your detailed review and consideration. I agree with your conclusion that utilizing only the @Getter annotation is the best approach given the current use of the class. Your analysis makes sense, and I support moving forward with this solution. I'll approve the PR based on this decision. LGTM!

2024-02-03 02:50 UTC, VampireAchao approved these changes

2024-02-03 02:50 UTC, merged